name             'role-mongodb-configserver'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures role-mongodb-configserver'
long_description 'Installs/Configures role-mongodb-configserver'
version          '0.1.3'

depends 'mongodb', '0.16.1'
depends 'yum'
